liferay-learn site | change header font size | LRDOCS-9182
jrhoun/liferay-learn pull request #1080
Opened 2021-06-24 15:04 UTC by rbohl

https://issues.liferay.com/browse/LRDOCS-9182
@rdai10 @thektan please approve or disapprove/do something smarter
cc @mtokudome

2021-06-24 15:12 UTC, rdai10 requested changes

2021-06-24 15:12 UTC, rdai10 commented on site/homepage/_static/scss/_custom_variable.scss
> -$h2-font-size: 1.5rem !default; // 24px
@rbohl how about keeping h2 at 1.5rem (24px), but updating h3 to 1.25rem (20px)? That way we stay with the grid system the UX department has defined. Can you also update the comment with pixel values so that it accurately reflects the actual font size?

2021-06-24 15:16 UTC, rbohl commented on site/homepage/_static/scss/_custom_variable.scss
> -$h2-font-size: 1.5rem !default; // 24px
Yeah that works for me :+1: 
While we're here: should we also increase the space between the H3 heading and the paragraph text?

2021-06-24 15:20 UTC, rdai10 commented on site/homepage/_static/scss/_custom_variable.scss
> -$h2-font-size: 1.5rem !default; // 24px
Do you mean line height? I don't see any specified for h2-h4, I think it's probably fine to leave it as is.

2021-06-24 15:46 UTC, rdai10 approved these changes

2021-06-24 17:30 UTC, thektan approved these changes
Looks good to me too. The hierarchy seems to be good with the current spacing.

(Removed some elements for the screenshot to get the headings closer together)
![Screen Shot 2021-06-24 at 10 29 47 AM](https://user-images.githubusercontent.com/4496722/123307236-1b89b980-d4d7-11eb-8478-e1aca4a8b287.png)

2021-07-02 17:58 UTC, jrhoun commented
Merged. Thank you everyone. Seeing the collaboration warms my ❤️ .

2021-07-02 17:58 UTC, closed without merging