[DXP Cloud] LRDOCS-9528 Add more explanation for adjusting liveness/readiness probes
jrhoun/liferay-learn pull request #1132
Opened 2021-08-10 20:19 UTC by Alec-Shay

See: https://issues.liferay.com/browse/LRDOCS-9528

This adds a lot more explanation as to what things users should consider when adjusting their probe configurations. It is a bit dense text-wise, but I'm not sure whether much can be done about that.

2021-08-10 20:43 UTC, timscottbell requested changes
Apart from my comments, I think it would be really helpful to mention that probes follow redirects, so ideally it's good to pick a http url that doesn't redirect to save on response time.

2021-08-10 20:43 UTC, timscottbell commented on docs/dxp-cloud/latest/en/troubleshooting/self-healing.md
> +If the probe gets an HTTP response in the 200 or 300 range, it marks the application as healthy. It fails if the instance is no longer live (for example, due to a crash). If the probe pings the path
I think there are more cases for liveness probe failure than just startup. Typically liveness probes are really meant to be used for deadlock, for example, when a service stop performing and hangs after it has been running for awhile. So the main use case is not startup, but our customers frequently experiences issues during startup because they don't set a long enough today. So I think what you're trying to get at here is warning customers not to have their liveness probes fail for the wrong reason during a startup.

2021-08-10 20:43 UTC, timscottbell commented on docs/dxp-cloud/latest/en/troubleshooting/self-healing.md
>  As soon as the readiness probe detects that the service is ready, then the service may receive traffic. If the probe detects that the service is no longer ready, then it will stop receiving new traff
Can we clarify here that only the livenessProbe restarts a service?

2021-08-10 20:43 UTC, timscottbell commented on docs/dxp-cloud/latest/en/troubleshooting/self-healing.md
> +The readiness probe should execute a command that appropriately gauges the health of your service. If your service is responding to requests too slowly and it needs to be cut off from more traffic, t
I don't think readinessProbes are about gauging the health of the service -- that's what liveness probes are for. Readiness probes are about whether your service is not capable of receiving traffic from the kubernetes endpoint.

2021-08-10 23:45 UTC, Alec-Shay commented
Pushed a new commit to address feedback from the services team (thanks @timscottbell!).

2021-08-11 16:38 UTC, jrhoun commented
Merged. Thanks.

2021-08-11 16:38 UTC, closed without merging